version: "3.8"

services:
  api:
    build: .
    container_name: api-manga-wurmz
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SOURCE_URL=${SOURCE_URL}
      - CORS_ORIGIN=*
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped
