services:
  - type: web
    name: api-manga-wurmz
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: SOURCE_URL
        value: https://wurmz.net
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: "*"
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_OWNER
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: DISCORD_WEBHOOK
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
